services:
  nginx:
    image: nginx:stable
    container_name: abi_nginx
    ports:
      - "8080:80" # Mapeia a porta 8080 para acesso ao Nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html  # Mapeia todo o projeto para /var/www/html no container
    depends_on:
      - php
      - mariadb
    networks:
      - abi-net

  php:
    build:
      context: ./docker/php
    container_name: abi_php
    volumes:
      - .:/var/www/html  # Mapeia todo o projeto para /var/www/html no container
    environment:
      - XDEBUG_MODE=coverage
      - XDEBUG_CONFIG="client_host=host.docker.internal"
    depends_on:
      - mariadb
    networks:
      - abi-net

  mariadb:
    image: mariadb:latest
    container_name: abi_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - abi-net

networks:
  abi-net:
    driver: bridge

volumes:
  mariadb_data:
